### ISSUE TITLE
Message to MarkFern

### ISSUE THREAD

**Issue by Linda-Editor** [MicrosoftDocs/VBA-Docs#1065]
@markfern FYI, I just learned that my contract is ending this Friday (no budget for FY20), so let me know if you need anything in the next day or so. Thanks...

**Comment by MarkFern** [comment]
@Linda-Editor, sorry to see you go. Is there no-one going to take over your job?

Because you are probably going to be busy in your last days, perhaps you could just give me some tips in relation to my edits @ https://github.com/MarkFern/VBA-Docs/blob/b49b52305e735611197327819ac8c0f6fde8fc77/Language/Reference/User-Interface-Help/data-type-summary.md ?

In particular, I sometimes have problems with grammar, punctuation, & sentence construction&mdash;don't particularly have a background in natural-language writing. Would be very useful if you could give me your point of view.

Thanks for all your help & I wish you the best for the future. 😊

**Comment by Linda-Editor** [comment]
@ The biggest issue I see with your writing is your use of the ampersand (&) instead of using "and". When writing text, always use "and"; save the & for code, etc. So you'll need to change all of those. The only other thing is that the page is starting to look very complex. I'm wondering if dividing the content into separate pages and linking to them from the data summary page might be a better option. What do you think?

**Comment by MarkFern** [comment]
Hello @Linda-Editor, yes, you're right about the complexity of the page. It's something that I have noticed. However, in terms of whether the information is relevant enough to be placed on the page, the information is as such. I'm not sure exactly what I will do but I may end up committing it as one page to start off, and then afterwards split the page up into separate pages.

Re. the use of '&', thanks for pointing this out. Is there any particular reason why '&' shouldn't be used in 'normal' text? I will change the text as you indicate but it would be useful to know the underlying reasoning behind having to make such changes.

Thanks.

**Comment by Linda-Editor** [comment]
Because "&" is not a word; it's a symbol.

**Comment by Linda-Editor** [comment]
Today's my last day, so closing this issue. Take care!

**Comment by MarkFern** [comment]
You too!
