### ISSUE TITLE
Please provide more info.

### ISSUE THREAD

**Issue by PBrady43** [MicrosoftDocs/VBA-Docs#627]
I understand that the #if mechanism is much more powerful but cannot find documentation.  Eg
#if (this version of Excel supports ribbon) then
#if (this workbook is an xlsm not xls file) then
#if (this is a Mac computer) then
#if Excel version is &gt; 11
That documentation would be so useful.
Phil B.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe15ef6-6f68-e7fa-117e-9dc56eb23e2c
* Version Independent ID: b3f194aa-0243-5520-c449-5911276e47bf
* Content: [Understanding conditional compilation (VBA)](https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/understanding-conditional-compilation)
* Content Source: [Language/Concepts/Getting-Started/understanding-conditional-compilation.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Concepts/Getting-Started/understanding-conditional-compilation.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by retailcoder** [comment]
#If directives are **pre-compilation** directives; as such they are rather limited in what they can access, because a compile-time identifier such as `ThisWorkbook` isn't accessible (yet) when these directives are processed.

The full list of built-in precompiler constants is well documented and complete: there are no others.

Your VBA project can define its own module-scoped #Const values that can then be accessed by precompiler directives, but these constants can't be assigned to expressions that need to be compiled.

Whether you're running on a Mac is one such precompiler constant; whether the VBA runtime is VBA6 or VBA7 is also one; whether the OS is 32 or 64 bits is also a precompiler constant - everything else isn't accessible at that time, including `Application.Version`.

Rule of thumb, precompiler directives are for allowing code to compile & run in different environments, e.g. VBA7 under Win64 can use the LongLong integer type, and Declare statements don't have a PtrSafe modifier in VBA6, and some DLLs might not exist on a Mac - without precompiler diectives such code could only run in the environment it was written in.

Conditional compilation doesn't substitute executable `If...Then` control flow.

**Comment by Linda-Editor** [comment]
@retailcoder  Thanks for the helpful feedback. Should we add this to the documentation?

@PBrady43 Does this info answer your question?

**Comment by PBrady43** [comment]
Dear Mathieu,
thank you for your reply.  Where is the full list of built-in precompiler constants?  A link to it from the #if page would help.
Regards
Phil Brady

________________________________

**Comment by PBrady43** [comment]
Dear Linda,
Thank you for your email.   I understand the concept of pre-compilation  and I was hoping that there would have been a link to the list of pre-compiler constants.
Regards
Phil Brady

________________________________

**Comment by Linda-Editor** [comment]
@PBrady43 Is this what you're looking for? https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/compiler-constants

**Comment by PBrady43** [comment]
Yes it was.   I think my problems were that:
a) there wasn't a link from the page which describes the #If directive
b) it was so much more limited than I imagined!   I was initially looking for a line
   #If (use of IRibbonControl is supported by the compiler) Then

Thanks for your response.
Phil Brady


________________________________

**Comment by Linda-Editor** [comment]
@PBrady43 Thanks. I cross-linked the "understanding" page and the "compiler constants" pages to each other. Changes will be live later today.
