### ISSUE TITLE
Example does not run?

### ISSUE THREAD

**Issue by mopwop2** [MicrosoftDocs/VBA-Docs#74]
Will this code example actually run?

Worksheets("Sheet1").Range.Item("A1:A10").FillDown

When attempting to run the code the result so far has been

Run-time error '450':
Wrong number of arguments or invalid property assignment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1053e438-b5d2-2558-e6f7-53de954f3bf0
* Version Independent ID: d21b790e-f6ed-c334-8d22-a075ca050cb5
* Content: [Range.Item Property (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.range.item#syntax)
* Content Source: [api/Excel.Range.Item.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Range.Item.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
Thanks for your feedback. We use Github issues for documentation bugs, not for developer support. Please try the VBA developer community on Stack Overflow (https://stackoverflow.com/questions/tagged/vba) where you can get help from actual developers. If you find a bug in our documentation, please let us know! Thanks!

**Comment by Linda-Editor** [comment]
@retailcoder 

Thanks. I updated the code on the page (replaced Range with Cells). Changes will be live later today.

**Comment by Linda-Editor** [comment]
@mopwop2 @EugenB01 @retailcoder  - Could you guys look at the information the these two pages to determine what the code string should be on the Range.Item property? It seems that both Rnage and Cells should be in the string: [Range.Cells](https://docs.microsoft.com/office/vba/api/excel.range.cells) and [Range.Range](https://docs.microsoft.com/office/vba/api/excel.range.range) properties

**Comment by retailcoder** [comment]
Coincidentally, I wrote about this on Stack Overflow just a few weeks ago ([here](https://stackoverflow.com/a/53839726/1188513)) - I doubt `Range.Item` was intended to be invoked directly: a parameterless `Range.Cells` returns the `Range` object it's invoked against: when you add arguments to `Range.Cells`, you're providing the optional arguments to the hidden `Range.[_Default]` member, aptly named for its member ID being 0, it is the class' *default member* - the one that's implicitly invoked whenever we can open parentheses against an object, directly: it's the implicit member call against `foo` in `a = foo(42)`. By convention, a collection class' default member will typically be named `Item` and accept some `Index` parameter.

The `Range` class is special in that it *acts* very much like a collection class, but its default member isn't straightforwardly the `Item` property, because, API design decisions were taken to make `myRange = 42` somehow assign to the `Value` property - making a hidden default member that could "redirect" a call to `Item` or to `Value` depending on context. It does make it easy to *write* VBA code that "works". Makes it much harder to *read* VBA code and know what's going on though.

So this is pure speculation on the implementation of that default property getter, but it *appears to* behave as follows:

 - When no arguments are provided, yields to the `Value` getter, which returns a `Variant` holding the cell's `Value`. The contents of this variant depends on the number of cells in the range: for multiple cells, we get a 2D `Variant` array holding the cells' values.
 - When arguments are provided, yields to the `Item` getter, which accepts row and column arguments.

Truth is, I don't know whether further API design decisions were taken to make that getter accept a string with a full range address instead of a numeric row number with an optional numeric column number - I would merrily encourage people to use the `Worksheet.Range` member (with an explicit worksheet qualifier) when they want to use a string address, and the `Cells` member (i.e. `Item`, through a default member call) when working with numeric rows and columns; I'd also recommend avoiding mixed use of string addresses and numeric row/column indices.

I realize this is *documentation* and the idea is to *document* usage, but assuming `Range.Item(string)` is supported, then maybe it's best to not bend over backwards to show a working example that basically shows how *not* to do things.

    ' don't do this:
    Sheet1.Cells.Item("A1:A10").FillDown

`Worksheet.Cells` shouldn't ever need to be invoked parameterless. If we want to use a string address, we use `Worksheet.Range` instead:

    ' do this instead:
    Sheet1.Range("A1:A10").FillDown

If we stick to this "string->Range/number->Cells" rule of thumb, then this becomes an example *proper* use of `Range.Item`:

    Sheet1.Range("A1:B10").Cells(i, 2) = 42

Which is, under the hood:

    Sheet1.Range("A1:B10").Cells.[_Default](i, 2).[_Default] = 42

Which seems to resolve to:

    Sheet1.Range("A1:B10").Cells.Item(i, 2).Value = 42

Hope it helps!
