### ISSUE TITLE
Unable to change font size in excel vba editor

### ISSUE THREAD

**Issue by gstazure** [MicrosoftDocs/VBA-Docs#85]
Unable to change font size. In courier western its set at 7 , and i cannot increase it. Arial cannot increase it more than 8. Every time it resets to font 7 ot 8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98489ee2-e346-4b57-4c54-b7537a93c29d
* Version Independent ID: 86458361-267d-82bf-8068-9638f9a3eb3a
* Content: [Editor Format Tab (Options Dialog Box)](https://docs.microsoft.com/en-us/office/vba/Language/Reference/User-Interface-Help/editor-format-tab-options-dialog-box)
* Content Source: [Language/Reference/User-Interface-Help/editor-format-tab-options-dialog-box.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/editor-format-tab-options-dialog-box.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@gstazure Thanks for your feedback. We use Github issues for documentation bugs, not for developer support. Please try the VBA developer community on Stack Overflow (https://stackoverflow.com/questions/tagged/vba) where you can get help from actual developers. If you find a bug in our documentation, please let us know! Thanks!

**Comment by retailcoder** [comment]
Hi, I manage the [Rubberduck](https://github.com/rubberduck-vba/Rubberduck) OSS VBIDE add-in project (written in C# 7, if you want to contribute), which you may want to watch, since we have it on our roadmap to implement a custom code pane with enhanced syntax highlighting and more font options. That custom code pane feature is scheduled for v3.0 (we're about to release v2.3, so little is done towards custom code panes at this point, but we'll definitely get there).

I don't think Microsoft has any plans to enhance the VBE in any way, or fix any problems with it - so 3rd-party IDE add-ins are your only sure shot at getting new or improved functionality into the VBA editor.
