### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#876]
Linda,
This week I indicated that a space was missing. I doubted whether I should report this to you. I thought it a little exaggerated to report this. I foresee that I will only bother you with such things, which of course should never be the intention. On the other hand, I know that you want the texts to be correct. But if it's not really urgent...
I suggest that I only report in such cases if it is important (per case). If you want, I can also collect less important cases and report that to you in one message. Just let me know what you appreciate. I want to help you as good as possible. In addition, I would like to give something back to Microsoft.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Hi Peter, thanks so much. As long as you file it as an ISSUE (vs. a PR), nothing is too small. I work in VBA-Docs every day, so it's already open and I can easily make the fix. It's okay to collect several issues in one issue if you want as well, but not necessary. Only use PRs if you have many changes across several docs (and these can all be in the same PR). The main reason for this is the repo itself; because it's so big, it takes an hour to build updates, vs. smaller repos that take only a few minutes. Thanks for helping us!

**Comment by PeterVanLoosbroek** [comment]
OK, clear en thanks.
