### ISSUE TITLE
Enum Type Name casing vs Enum Value Name casing

### ISSUE THREAD

**Issue by 5even** [MicrosoftDocs/VBA-Docs#966]
Good Morning,

_This is a bit trivial, but does offer an opportunity to improve the documentation's clarity._

The excel VBA framework seems to have a convention for beginning enumeration names with uppercase letters and their value names with lowercase.  (https://docs.microsoft.com/en-us/office/vba/api/overview/excel/enumerations-graph-visual-basic-reference)

The documentation doesn't always adhere to the convention.  

For instance: https://docs.microsoft.com/en-us/office/vba/api/excel.range.find#parameters

In the parameter descriptions, both enumeration names (i.e. 'XlLookAt', 'XlFileLookIn', etc) and their associated value names (i.e. 'xlWhole', 'xlPart', 'xlFormulas', etc.) begin in the lower case.  It would be more accurate for enumeration names to begin with an uppercase 'X'.

**Comment by Linda-Editor** [comment]
@5even Yes, you're right. We're in the process of fixing these as we find them. I thought I fixed all the ones that are contained in the links, but I guess not. I'll do another search/replace right now. However, the ones not linked have to be done as we find them, so that we don't accidentally uppercase a constant. Thanks for mentioning this.
