### ISSUE TITLE
Missing documentation on custom collection classes

### ISSUE THREAD

**Issue by MarkFern** [MicrosoftDocs/VBA-Docs#977]
I've modified a branch on my fork to document better what collections are. I've also added to the branch an example of how to create your own collection class. 

The branch is a patch of related commits and is stored [here](https://github.com/MarkFern/VBA-Docs/tree/MF-PATCH_For-Each-over-custom-collection-classes-defined-by-user).

Please consider applying the commits in the patch to the Microsoft repository.

Ideally, even more documentation needs to be added in regard to this area.

**Comment by Linda-Editor** [comment]
@MarkFern I can't tell which documents you've created or modified just by going to your fork/branch. So the best way to submit them is to do a pull request where I can see what you did and can decide whether to merge the PR. Can you give me a rough example of the documents you've created or modified?

**Comment by MarkFern** [comment]
Hello **@Linda-Editor**.

Only 2 documents modified:  slight change to [VBE glossary](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Glossary/vbe-glossary.md) & example added to ['Using For Each...' page](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Concepts/Getting-Started/using-for-eachnext-statements.md). There are only two commits in the patch.

I figured out how you can view just my commits on the branch, from a _StackOverflow_ post shown [here](https://stackoverflow.com/a/53848100/11208356).

Click [here](https://github.com/MarkFern/VBA-Docs/commits/MF-PATCH_For-Each-over-custom-collection-classes-defined-by-user?author=MarkFern) to see just my commits to the patch.

Do you still want me to create a _PR_?

**Comment by Linda-Editor** [comment]
@MarkFern Mark, this is the type of item that you should submit PRs for. Please create two PRs, one for each page that you updated. That way I can choose to make the change manually or merge your PRs. Thanks!

**Comment by MarkFern** [comment]
> @MarkFern Mark, this is the type of item that you should submit PRs for. Please create two PRs, one for each page that you updated. That way I can choose to make the change manually or merge your PRs. Thanks!

@Linda-Editor, PRs #979 & #980 have been created to replace this ISSUE. as requested by yourself.

---

### Off Topic

***Can you please confirm whether PRs for this repository should never modify more than one page?***

It might be worthwhile writing a guidance document for contributors (like the one for the GitHub repository for the .NET documentation). Previously you told me to create ISSUEs instead of PRs. The first time you said not to create a PR if the change is small and the second time, you said to create ISSUEs for glossary changes. It's slightly confusing. Please elaborate on what you consider to be a small change and what you consider to not be a small change.

Thanks.

**Comment by Linda-Editor** [comment]
@MarkFern Sorry for the confusion about issues and PRs. My guidance only applies to this repo, and it's based on the fact that because this repo is so big (37K+ files), one merge of a PR kicks off a one-hour build (whereas in other repos it only takes a few minutes, so is not a big deal). That's why if you have a small change, I prefer that you submit it as an issue, and then it bypasses that merge. I wasn't clear what you wanted for each of these, and that's why I asked you to submit them as two separate PRs, so I could decide to merge one and not the other if need be. For future reference, the one glossary change could be submitted as an issue (but I'll handle it). If you're making many changes in the glossary (such as when you combine the two glossaries), that's better to do in a PR. Again, this guidance only applies to this repo. In other repos, follow the guidance they give you. And yes, you can submit more than one page in a PR. It's just that I wasn't quite sure what your changes were. Thanks, and I hope this clarifies things.
