### ISSUE TITLE
Missing items re: Application.OnKey Method

### ISSUE THREAD

**Issue by mcomp72** [MicrosoftDocs/VBA-Docs#982]
This is my first time posting on Github.  I was not sure if I should submit this an an ISSUE or PULL REQUEST.

Referring to this page:
https://docs.microsoft.com/en-us/office/vba/api/Excel.Application.OnKey

There is no listing for the COMMAND button on Mac.  I know that on Excel 2011 for Mac, the way to reference if the COMMAND button is pressed is with '*'.  For instance, for detecting COMMAND & the 'c' key, it would be:
Application.OnKey "*c"

Firstly, that is not listed on the page, and should be.

Secondly, and more importantly, that code does not work on Excel 2016/2019 for Mac, so it would be helpful to see on this page what character should be used in the code to detect COMMAND press on those Excel versions.

**Comment by Linda-Editor** [comment]
@mcomp72 Thanks for this submission. It's okay to submit small changes as Issues, rather than PRs, because this repo is so big (one merge of a PR kicks off a one-hour build, whereas for smaller repos, it only takes a few minutes). 

That said, could you let me know where exactly on the page you'd like me to add your guidance? For example, let me know which table you expect this to appear in, and give me the item appearing before and after where you'd like it entered.

For your second question, first check with Stack Overflow (https://stackoverflow.com/questions/tagged/vba). Some of the pages in this repo haven't been updated for the latest versions, so I'm not sure what the correct character should be. If you find out on Stack Overflow, send me the info and we'll get the page updated. Thanks.

**Comment by mcomp72** [comment]
Hi Linda.  Thanks for the reply.

For where to add the info: under REMARKS, there is a section that begins "You can also specify keys combined with...".  I would list the Command button under the other three in that section, and then make a note that that is only for Mac.  I would also make a note indicating that it may only work on Excel 2011 for Mac.

Speaking on that point, I have searched not only Stack Overflow (as well as added my own post to ask this specific question), but also Google in general, looking for how to detect Command press on Excel 2016/2019 for Mac.  I have had absolutely no luck in finding the answer.  I have seen earlier forum posts from other people asking the same question, but no responses contain the correct answer.  I am wondering if Microsoft removed the ability to detect that button press starting in Excel 2016?  (It would seem rather odd if they did.)  Do you have any way to check with the engineers at Microsoft to find out?

**Comment by Linda-Editor** [comment]
@mcomp72 I'll see what I can do about finding the answer to your question. In the meantime, I'll update the page; changes should be live by tonight.

**Comment by Linda-Editor** [comment]
@MattKeMS Would you know the answer to this question, or could you point us to someone who could answer it? See the question earlier in this thread. Thanks.

**Comment by Linda-Editor** [comment]
@mcomp72 Here's what I added; let me know if anything needs to be changed:

|To combine keys with|Precede the key code by|
|:-----|:-----|
|Shift| `+` (plus sign)|
|Ctrl| `^` (caret)|
|Alt| `%` (percent sign)|
|Command|`*` (asterisk) Only applies to Mac; may only work on Excel 2011 for Mac and not later versions.|

**Comment by mcomp72** [comment]
Hi Linda.  The only other thing I can think of is in the sentence above, you could add the bit about Command, like so:

You can also specify keys combined with Shift and/or Ctrl and/or Alt and/or Command. To specify a key combined with another key or keys, use the following table.

**Comment by MattKeMS** [comment]
Hi @mcomp72  and @Linda-Editor, I checked with engineers that own this area. They verified that there is no way to currently detect the Command key in recent versions of Office VBA.  But they consider this a bug, since it works in Excel 2011, and will try to address and fix it in the future.  Thank you for bringing this to our attention!

**Comment by Linda-Editor** [comment]
@MattKeMS Thanks so much for tracking down this answer! Should we add a note to the VBA page so that future users are aware that we're working on it?

**Comment by MattKeMS** [comment]
You are welcome.  I think that would be fine to add a note like that, in case other Excel OM customers have a similar question about this behavior.

**Comment by Linda-Editor** [comment]
Thanks. Here's the note I propose to add; I'm trying to keep it so it's not promising anything; let me know if you want me to tweak it in any way.
 
> [!NOTE] 
> There is no way to currently detect the Command key in recent versions of Office VBA. Microsoft is aware of this and is looking into it.

**Comment by Linda-Editor** [comment]
@mcomp72 Changes from yesterday are now live: https://docs.microsoft.com/en-us/office/vba/api/excel.application.onkey

**Comment by Linda-Editor** [comment]
@MattKeMS Perfect, Matt! Thanks!

**Comment by mcomp72** [comment]
Thanks to you both for your help on this!  :)

**Comment by Linda-Editor** [comment]
@mcomp72 @MattKeMS All the requested changes are now live at https://docs.microsoft.com/en-us/office/vba/api/Excel.Application.OnKey, so closing this issue. Matt, you'll still be able to comment on this when the bug is fixed by searching for it in the repo with the issue # 982. Thanks to both of you for your help with this.
